spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modus
    username: modus
    password: modus
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true