
spring:
  datasource:
    url: jdbc:postgres://localhost:5432/modus
    username: modus
    password: modus
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
